### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by aditya-singhal** [glennramalho/espmod#1]
I am getting a compilation error while doing make in the main project directory.
**Error:
src/cores/esp32-hal-spi.cpp:48:27: fatal error: soc/dport_reg.h: No such file or directory
compilation terminated**.
![error](https://user-images.githubusercontent.com/18501610/85209545-877e9280-b356-11ea-8406-7155890e2f99.png)

**Comment by glennramalho** [comment]
Good to see someone else is trying to use the model. I use it everyday but so far it is just me.
Anyways, sorry about that. I guess I had forgotten to check in two files. Done now.

regards
Glenn

**Comment by aditya-singhal** [comment]
Ok. I'll check it now.

**Comment by aditya-singhal** [comment]
Hi Glenn,
I have recently learned the SystemC and TLM language. So, I was looking for
some model code for better understanding of the language.
Ok. I'll check it now.

Regards,
Aditya

**Comment by aditya-singhal** [comment]
Compilation success. Thanks.
